---
title: "Group Tidy"
author: "Group 13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(ggplot2)
```

#1 
```{r}
tax <- tribble(
  ~ Country,     ~ `1970`, ~ `1979`,
  "Sweden",          46.9,     57.4,
  "Netherlands",     44.0,     55.8,
  "Norway",          43.5,     52.2,
  "Britain",         40.7,     39.0,
  "France",          39.0,     43.4,
  "Germany",         37.5,     42.9,
  "Belgium",         35.2,     43.2,
  "Canada",          34.9,     35.8,
  "Finland",         34.9,     38.2,
  "Italy",           30.4,     35.7,
  "United States",   30.3,     32.5,
  "Greece",          26.8,     30.6,
  "Switzerland",     26.5,     33.2,
  "Spain",           22.5,     27.1,
  "Japan",           20.7,     26.6
)
```

```{r}
tax
```



```{r}
taxes <- tax %>% pivot_longer(c(`1970`, `1979`), names_to = "Year", values_to = "Value")
```


```{r}
ggplot(taxes) +
  geom_line(mapping = aes(x = Year, y = Value, group = Country))


```


#2

```{r}
filled.contour(volcano, color.palette = terrain.colors, asp = 1)
```
```{r}
volcano_tbl <- as_tibble(volcano)

colnames(volcano_tbl) <- 1:ncol(volcano) 
volcano_tbl$row <- 1:nrow(volcano_tbl)

volcano_tbl
```

```{r}
# https://r-graph-gallery.com/79-levelplot-with-ggplot2.html

volcano_tbl %>%
  pivot_longer(cols = 1:61, names_to = "axis", values_to = "elevation") %>%
  mutate(axis=as.numeric(gsub("V","",axis))) %>%

  ggplot(aes(row, axis, fill= elevation)) + 
    geom_tile() +
    scale_fill_gradientn(colours = terrain.colors(7)) +
    xlab(" ") + ylab(" ")
```




#3

```{r}
budget <- tribble(
  ~ Expenses,             ~ Jan, ~ Feb, ~ Mar, ~ Apr, ~ May, ~ Jun, ~ Jul, ~ Aug, ~ Sep, ~ Oct, ~ Nov, ~ Dec,
  "Domestic Actual",      84853, 84838, 88103, 85072, 88723, 90384, 89374, 95273, 94239, 92394, 96934, 105034,
  "Domestic Budget",      83000, 83830, 84668, 85515, 86370, 87234, 88106, 88987, 89877, 90776, 91684, 92600,
  "International Actual", 12538, 12438, 14934, 14033, 13945, 15938, 14086, 15934, 13945, 17338, 19384, 22394,
  "International Budget", 12000, 12600, 13860, 13200, 13860, 15246, 14520, 15246, 16771, 15972, 16771, 18448
)
```





